/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the tdd-app SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx healthGetHealth.example.ts
 */

import { TddApp } from "tdd-app";

const tddApp = new TddApp();

async function main() {
  const result = await tddApp.health.getHealth();

  console.log(result);
}

main().catch(console.error);
