apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: frontend-build-test-
  namespace: tdd-tekton-pipelines

spec:
  pipelineRef:
    name: frontend-build-test

  workspaces:
    - name: source
      emptyDir: {}