/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { challengesGetChallenge } from "../funcs/challenges-get-challenge.js";
import { challengesListChallenges } from "../funcs/challenges-list-challenges.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Challenges extends ClientSDK {
  /**
   * Get all challenges
   *
   * @remarks
   * Returns all available TDD challenges.
   */
  async listChallenges(
    options?: RequestOptions,
  ): Promise<Array<models.Challenge>> {
    return unwrapAsync(challengesListChallenges(
      this,
      options,
    ));
  }

  /**
   * Get challenge by ID
   *
   * @remarks
   * Returns a single TDD challenge using its string ID.
   */
  async getChallenge(
    request: operations.GetChallengeRequest,
    options?: RequestOptions,
  ): Promise<models.Challenge> {
    return unwrapAsync(challengesGetChallenge(
      this,
      request,
      options,
    ));
  }
}
