/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Challenges } from "./challenges.js";
import { Health } from "./health.js";

export class TddApp extends ClientSDK {
  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _challenges?: Challenges;
  get challenges(): Challenges {
    return (this._challenges ??= new Challenges(this._options));
  }
}
