apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation

metadata:
  name: tdd-react-frontend
  namespace: flux-system

spec:
  interval: 1m

  sourceRef:
    kind: GitRepository
    name: tdd-project

  git:
    checkout:
      ref:
        branch: main

    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com

      messageTemplate: |
        Update frontend image

    push:
      branch: main

  update:
    path: ./devops/flux/applications/frontend
    strategy: Setters