apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bootstrap/infrastructure-kustomization.yaml
  - bootstrap/keda-kustomization.yaml
  - bootstrap/kyverno-kustomization.yaml
  - bootstrap/openbao-kustomization.yaml
  - bootstrap/applications-kustomization.yaml