apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-sha
  namespace: tdd-tekton-pipelines

spec:
  description: Generate a timestamped Git commit tag.

  workspaces:
    - name: source

  results:
    - name: image-tag
      description: Timestamped Git commit tag.

  steps:
    - name: generate-tag
      image: alpine/git:2.47.2
      workingDir: $(workspaces.source.path)

      script: |
        #!/bin/sh
        set -eu

        SHA="$(git rev-parse --short=7 HEAD)"
        TIMESTAMP="$(date -u +%Y%m%d%H%M%S)"

        TAG="${TIMESTAMP}-${SHA}"

        echo "Git commit SHA: $SHA"
        echo "Image tag: $TAG"

        printf "%s" "$TAG" > "$(results.image-tag.path)"