/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetChallengeRequest = {
  /**
   * Unique challenge ID.
   */
  id: string;
};

/** @internal */
export type GetChallengeRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetChallengeRequest$outboundSchema: z.ZodMiniType<
  GetChallengeRequest$Outbound,
  GetChallengeRequest
> = z.object({
  id: z.string(),
});

export function getChallengeRequestToJSON(
  getChallengeRequest: GetChallengeRequest,
): string {
  return JSON.stringify(
    GetChallengeRequest$outboundSchema.parse(getChallengeRequest),
  );
}
