/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Difficulty level of the challenge.
 */
export const Difficulty = {
  Beginner: "Beginner",
  Intermediate: "Intermediate",
  Advanced: "Advanced",
} as const;
/**
 * Difficulty level of the challenge.
 */
export type Difficulty = OpenEnum<typeof Difficulty>;

export type Challenge = {
  /**
   * Unique identifier of the challenge.
   */
  id: string;
  /**
   * Challenge title.
   */
  title: string;
  /**
   * Description of the challenge.
   */
  description: string;
  /**
   * Difficulty level of the challenge.
   */
  difficulty: Difficulty;
  /**
   * Concepts covered by the challenge.
   */
  concepts: Array<string>;
  /**
   * Steps involved in completing the challenge.
   */
  steps: Array<string>;
};

/** @internal */
export const Difficulty$inboundSchema: z.ZodMiniType<Difficulty, unknown> =
  openEnums.inboundSchema(Difficulty);

/** @internal */
export const Challenge$inboundSchema: z.ZodMiniType<Challenge, unknown> = z
  .object({
    id: types.string(),
    title: types.string(),
    description: types.string(),
    difficulty: Difficulty$inboundSchema,
    concepts: z.array(types.string()),
    steps: z.array(types.string()),
  });

export function challengeFromJSON(
  jsonString: string,
): SafeParseResult<Challenge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Challenge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Challenge' from JSON`,
  );
}
