workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    TDD Challenge API:
        inputs:
            - location: ../../backend/openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/dataxis-labs/tddapp/tdd-challenge-api
targets:
    tdd-app:
        target: typescript
        source: TDD Challenge API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/dataxis-labs/tddapp/tdd-challenge-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
